#!/usr/bin/env python3

from mars2020 import mars2020api as mapi
from mars2020 import image_processing as imp
import typing as ty
from pathlib import Path
from dataclasses import dataclass
import PySimpleGUI as pg


@dataclass
class Parameters:
    sol: ty.Union[None, int] = None
    output_directory: str = "grid_output"
    save_as_layers: bool = False
    camera: ty.Union[None, str] = None
    grid_size: int = 16


def save_clusters(image_data: mapi.ImageDataCollection, parameters: Parameters):
    images: ty.List[mapi.ImageData] = list()
    for image in image_data.images:
        if image.instrument_metadata.thumbnail != "T":
            if (parameters.sol is None
                    and parameters.camera is None):
                images.append(image)
            elif (
                parameters.sol is None
                and image.camera_type.instrument == parameters.camera
            ):
                images.append(image)
            elif (
                parameters.camera is None
                and image.sol == parameters.sol
            ):
                images.append(image)
    image_clusters = imp.get_image_clusters(images, cluster_length=parameters.grid_size)
    if len(image_clusters):
        pg.Print(len(image_clusters), "images clusters were found")
    else:
        pg.Print("No image clusters were found")
    output_directory = Path(parameters.output_directory)
    if not output_directory.exists():
        output_directory.mkdir()
    for i, cluster in enumerate(image_clusters):
        if not parameters.save_as_layers:
            pg.Print(f"processing cluster {i + 1}...")
            imp.grid_from_4x4_imageset(cluster) \
                .save(output_directory / f"{cluster[0].image_id[:-8]}.png", format="PNG")
        else:
            for layer_id, layer in enumerate(imp.grid_from_4x4_imageset_with_layers(cluster)):
                layer_path = Path(output_directory / cluster[0].image_id[:-8])
                if not layer_path.exists():
                    layer_path.mkdir()
                layer.save(layer_path / f"layer-{layer_id}.png", format="PNG")
        pg.Print(f"saved cluster {i + 1} to {output_directory.as_posix()}")


def main_gui():
    pg.Print("Loading data from internets..")
    image_data: mapi.ImageDataCollection = mapi.ImageDataCollection.fetch_all_mars2020_imagedata()
    sols = ["all"] + list({x.sol for x in image_data.images})
    grid_size = [str(x**2) for x in range(1, 5)]
    cameras = ["all"] + list({x.camera_type.instrument for x in image_data.images})
    params = Parameters()
    layers = [[pg.Text("Choose output folder"), pg.FolderBrowse(button_text="Browse", key="output_path")],
              [pg.Text("Grid size"), pg.DropDown(values=grid_size, key="grid_size")],
              [pg.Text("Sol num."), pg.DropDown(values=sols, key="sol", default_value="all")],
              [pg.Text("Camera ID"), pg.DropDown(values=cameras, key="camera", default_value="all")],
              [pg.Checkbox("Save as separate layers", key="layers")],
              [pg.OK("OK"), pg.Cancel("Cancel")]]
    window = pg.Window("Perseverance rover image grid constructor", layers)
    while True:
        event, values = window.read()
        if event in [pg.WIN_CLOSED, 'Cancel']:
            break
        elif event == "OK":
            pg.Print("Processing images. This can take a few minutes")
            params.sol = None if values["sol"] is "all" else int(values["sol"])
            params.output_directory = values["output_path"]
            params.save_as_layers = values["layers"]
            params.camera = None if values["camera"] is "all" else values["camera"]
            params.grid_size = int(values["grid_size"])
            save_clusters(image_data, params)
    window.close()


if __name__ == "__main__":
    main_gui()
